### ISSUE TITLE
app-linux-input-proxy v1.0.26 (r4.2)

### ISSUE THREAD

**Issue by fepitre** [QubesOS/updates-status#2935]
Update of app-linux-input-proxy to v1.0.26 for Qubes r4.2, see comments below for details.

Built from: https://github.com/QubesOS/qubes-app-linux-input-proxy/commit/a58d3a158ccc1996326a13fc3e99490efa3ac0a1

[Changes since previous version](https://github.com/QubesOS/qubes-app-linux-input-proxy/compare/v1.0.25...v1.0.26):
QubesOS/qubes-app-linux-input-proxy@a58d3a1 version 1.0.26
QubesOS/qubes-app-linux-input-proxy@e252dbe debian: use USRLIBDIR instead of patch

Referenced issues:

If you're release manager, you can issue GPG-inline signed command:

* `Upload app-linux-input-proxy a58d3a158ccc1996326a13fc3e99490efa3ac0a1 r4.2 current repo` (available 7 days from now)
* `Upload app-linux-input-proxy a58d3a158ccc1996326a13fc3e99490efa3ac0a1 r4.2 current (dists) repo`, you can choose subset of distributions, like `vm-fc24 vm-fc25` (available 7 days from now)
* `Upload app-linux-input-proxy a58d3a158ccc1996326a13fc3e99490efa3ac0a1 r4.2 security-testing repo`

Above commands will work only if packages in current-testing repository were built from given commit (i.e. no new version superseded it).

**Comment by fepitre** [comment]
Package for fc32 was built ([build log](https://github.com/QubesOS/build-logs/tree/master/work-qubesos/log_2022-05-08_17-40-50)) and uploaded to current-testing repository

**Comment by fepitre** [comment]
Package for bullseye was built ([build log](https://github.com/QubesOS/build-logs/tree/master/work-qubesos/log_2022-05-08_17-40-50.1)) and uploaded to current-testing repository

**Comment by marmarek** [comment]
Superseded by #3058
