### ISSUE TITLE
[Meta] Disambiguate "testing" between current-testing, security-testing, and unstable

### ISSUE THREAD

**Issue by andrewdavidwong** [QubesOS/updates-status#320]
We have three different testing repos each for [dom0](https://www.qubes-os.org/doc/software-update-dom0/#testing-repositories) and [TemplateVMs](https://www.qubes-os.org/doc/software-update-vm/#testing-repositories): `current-testing`, `security-testing`, and `unstable`. Our automated build process (which creates issues in this repo) does not distinguish between these three, instead using the ambiguous term "testing." We should use the correct, precise name for each kind of testing repo to avoid confusion.

For example:
* #319 has the label `r4.0-dom0-testing`. Which dom0 testing repo does this refer to?
* https://github.com/QubesOS/updates-status/issues/319#issuecomment-349508266 says, "[...] uploaded to testing repository." Which testing repo was it uploaded to?

**Comment by andrewdavidwong** [comment]
CC: @marmarek

**Comment by marmarek** [comment]
IMO label like `r4.0-dom0-current-testing` would be too long for github UI, for some packages it doesn't fit in one line on issues list (see https://github.com/QubesOS/updates-status/issues/305 for example).
But making comment more precise is a good idea.

**Comment by andrewdavidwong** [comment]
You could abbreviate them to some reasonable length, e.g.,
* `r4.0-dom0-cur-test`
* `r4.0-dom0-sec-test`
* `r4.0-dom0-unstable`
